### ISSUE TITLE
Sig faults and general blanks

### ISSUE THREAD

**Issue by Mcrozier5609** [LoganConnor/Thompson_CSCI2270_FinalProject#3] opened 2015-05-01 21:55 UTC
When I try to run this code, I fear there may be an error on my end though, I get to the menu and then nothing really seems to work for me. Option 1 doesn't show the cars, so I put in a number for the car, then after I choose my starting and ending cities, I get sig faults. Option 2 doesn't show anything. Option three prompts me for the time, but no matter how much time I put in it always says there is no where I can drive to within distance. Option 4 does't show anything. Quit works fine though. Also, you need C++ 11 in codeblocks to be checked in the build option in order to use stoi, so you should mention that in the read me. Cool idea though!

**Comment by LoganConnor** [comment] 2015-05-02 02:50
The first thing you should check is that you have all the text files available. We have had three people now run the code and not see any of these errors, so I think the code is fine and it is an issue on your end. We will add the note on stoi to the Read Me, thanks!

**Comment by LoganConnor** [comment] 2015-05-03 20:39
If you cannot reliably produce then my guess is that the issue is that you did not have the text files available, so I will close this. Please open another issue if you think there is an actual bug in the code, but given that none of the other reviewers saw such obvious errors my guess is that you just need to make files available. Thanks!

**Closed as completed by LoganConnor** 2015-05-03 20:39 UTC
